### ISSUE TITLE
Feature: break lines on all diagnostics

### ISSUE THREAD

**Issue by artsbentley** [rachartier/tiny-inline-diagnostic.nvim#73]
I am loving the plugin! I was wondering if currently it is possible to break/wrap the diagnostics of *all* lines, versus only the diagnostic of where the cursor is currently at. Ideally it would be a toggling function

**Comment by rachartier** [comment]
Hello, thanks!

No, this is not possible, as diagnostics can overlap. I did try to mess with it quite a lot, but nothing looked good or was readable, so I decided not to continue with this.

Enabling diagnostics on all lines is more of a "hint" that a problem is on the line, rather than a debugging thing.
